/** Input submitted by the sign-in form. */
export interface SignInInput {
  /** User email address. */
  email: string;
  /** User password. */
  password: string;
}

/** Input submitted by the sign-up form. */
export interface SignUpInput {
  /** User display name. */
  name: string;
  /** User email address. */
  email: string;
  /** User password. */
  password: string;
  /** Optional backend avatar color token. */
  avatarColor?: string;
}

/** Authenticated user summary normalized for the frontend. */
export interface AuthUser {
  /** Unique user identifier. */
  id: string;
  /** User display name. */
  name: string;
  /** User email address. */
  email: string;
  /** Initials generated by the backend when available. */
  initials?: string;
  /** Avatar color token generated or accepted by the backend. */
  avatarColor?: string;
  /** ISO timestamp for user creation when returned by the backend. */
  createdAt?: string;
  /** ISO timestamp for the last user update when returned by the backend. */
  updatedAt?: string;
}

/** Authenticated session normalized across REST and GraphQL backends. */
export interface AuthSession {
  /** Bearer access token returned by the backend. */
  token: string;
  /** Authenticated user associated with the token. */
  user: AuthUser;
}

/** Successful authentication result returned by auth clients. */
export type AuthResult = AuthSession;

/** Validation errors keyed by frontend field name. */
export type AuthFieldErrors = Record<string, string[]>;

/** Normalized API error shape exposed to UI components. */
export interface ApiError {
  /** Human-readable error message safe for display. */
  message: string;
  /** Optional HTTP status code or equivalent GraphQL extension status. */
  statusCode?: number;
  /** Optional machine-readable backend error code. */
  code?: string;
  /** Optional normalized field validation errors. */
  fieldErrors?: AuthFieldErrors;
}

/** Contract implemented by REST and GraphQL auth clients. */
export interface AuthClient {
  /**
   * Registers a new user and returns an authenticated session.
   *
   * @param input - Sign-up form input.
   * @returns A normalized authenticated session.
   */
  signUp(input: SignUpInput): Promise<AuthResult>;
  /**
   * Authenticates an existing user and returns an authenticated session.
   *
   * @param input - Sign-in form input.
   * @returns A normalized authenticated session.
   */
  signIn(input: SignInInput): Promise<AuthResult>;
  /**
   * Ends the current frontend session.
   *
   * Backends currently expose bearer-token auth without a logout endpoint, so
   * implementations may resolve locally.
   */
  signOut(): Promise<void>;
  /**
   * Loads the current authenticated user using the stored bearer token.
   *
   * @returns A normalized user, or null when no valid session exists.
   */
  getCurrentUser(): Promise<AuthUser | null>;
}
