import type { CollaborationTextOperation } from '../types/collaboration.types';

/** Stable operation identity used for deterministic insert/insert tie-breaking. */
export interface OperationIdentity {
  /** Browser/client instance identifier. */
  clientId: string;
  /** Operation identifier generated by the client. */
  opId: string;
}

/**
 * Converts a JavaScript UTF-16 offset into a Unicode code-point offset.
 *
 * @param value - Source string.
 * @param offset - UTF-16 code-unit offset.
 * @returns Code-point offset used by the collaboration protocol.
 */
export function codeUnitOffsetToCodePointOffset(value: string, offset: number): number {
  return Array.from(value.slice(0, clamp(offset, 0, value.length))).length;
}

/**
 * Converts a Unicode code-point offset into a JavaScript UTF-16 offset.
 *
 * @param value - Source string.
 * @param offset - Code-point offset used by the collaboration protocol.
 * @returns UTF-16 code-unit offset used by CodeMirror.
 */
export function codePointOffsetToCodeUnitOffset(value: string, offset: number): number {
  return Array.from(value).slice(0, clamp(offset, 0, Array.from(value).length)).join('').length;
}

/**
 * Counts Unicode code points in a string.
 *
 * @param value - Text to measure.
 * @returns Code-point length.
 */
export function codePointLength(value: string): number {
  return Array.from(value).length;
}

/**
 * Applies an already transformed operation to plain text.
 *
 * @param content - Current plain text.
 * @param op - Insert/delete operation.
 * @returns Updated plain text.
 */
export function applyTextOperation(
  content: string,
  op: CollaborationTextOperation,
): string {
  const pos = clamp(op.pos, 0, codePointLength(content));
  const from = codePointOffsetToCodeUnitOffset(content, pos);

  if (op.type === 'insert') {
    return `${content.slice(0, from)}${op.text}${content.slice(from)}`;
  }

  const to = codePointOffsetToCodeUnitOffset(content, pos + op.len);
  return `${content.slice(0, from)}${content.slice(to)}`;
}

/**
 * Transforms an incoming operation over an accepted operation.
 *
 * Same-position insert/insert conflicts are deterministic: the smaller
 * `(clientId, opId)` key stays left, while the larger key shifts right.
 *
 * @param incoming - Operation being transformed.
 * @param incomingIdentity - Stable identity for the incoming operation.
 * @param accepted - Operation already accepted into server history.
 * @param acceptedIdentity - Stable identity for the accepted operation.
 * @returns Transformed operation, or null when a delete is fully covered.
 */
export function transformTextOperation(
  incoming: CollaborationTextOperation,
  incomingIdentity: OperationIdentity,
  accepted: CollaborationTextOperation,
  acceptedIdentity: OperationIdentity,
): CollaborationTextOperation | null {
  const next = { ...incoming };

  if (next.type === 'insert' && accepted.type === 'insert') {
    if (
      accepted.pos < next.pos ||
      (accepted.pos === next.pos &&
        compareIdentity(acceptedIdentity, incomingIdentity) < 0)
    ) {
      return { ...next, pos: next.pos + codePointLength(accepted.text) };
    }

    return next;
  }

  if (next.type === 'insert' && accepted.type === 'delete') {
    if (accepted.pos < next.pos) {
      return { ...next, pos: Math.max(accepted.pos, next.pos - accepted.len) };
    }

    return next;
  }

  if (next.type === 'delete' && accepted.type === 'insert') {
    const insertedLength = codePointLength(accepted.text);

    if (accepted.pos <= next.pos) {
      return { ...next, pos: next.pos + insertedLength };
    }

    if (next.pos < accepted.pos && accepted.pos < next.pos + next.len) {
      return { ...next, len: next.len + insertedLength };
    }

    return next;
  }

  if (next.type === 'delete' && accepted.type === 'delete') {
    const aEnd = next.pos + next.len;
    const bEnd = accepted.pos + accepted.len;

    if (bEnd <= next.pos) {
      return { ...next, pos: Math.max(0, next.pos - accepted.len) };
    }

    if (accepted.pos >= aEnd) {
      return next;
    }

    const overlapStart = Math.max(next.pos, accepted.pos);
    const overlapEnd = Math.min(aEnd, bEnd);
    const overlap = Math.max(0, overlapEnd - overlapStart);
    const length = Math.max(0, next.len - overlap);

    if (length === 0) {
      return null;
    }

    return {
      ...next,
      len: length,
      pos: accepted.pos < next.pos ? accepted.pos : next.pos,
    };
  }

  return next;
}

/**
 * Compares operation identities using the documented tie-breaker order.
 *
 * @param left - First identity.
 * @param right - Second identity.
 * @returns Negative when left sorts before right, positive when after.
 */
function compareIdentity(left: OperationIdentity, right: OperationIdentity): number {
  const leftKey = `${left.clientId}:${left.opId}`;
  const rightKey = `${right.clientId}:${right.opId}`;
  return leftKey.localeCompare(rightKey);
}

/**
 * Clamps a number to an inclusive range.
 *
 * @param value - Number to clamp.
 * @param min - Inclusive minimum.
 * @param max - Inclusive maximum.
 * @returns Clamped number.
 */
function clamp(value: number, min: number, max: number): number {
  return Math.max(min, Math.min(value, max));
}
